# Generated by Django 4.0.1 on 2022-01-06 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='contact_name')),
                ('subject', models.CharField(max_length=50, verbose_name='contact_subject')),
                ('email', models.EmailField(max_length=254, verbose_name='contact_email')),
                ('message', models.TextField(verbose_name='contact_message')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'ContactUs',
                'verbose_name_plural': 'ContactUs',
                'ordering': ['created'],
            },
        ),
    ]
